apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: martin-api-v3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: martin-api
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: martin-api
        version: v1
    spec:
      containers:
      - image: martinacrdev.azurecr.io/martin-api-alpine:v3
        imagePullPolicy: Always
        name: martin-api
        resources: {}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: martin-api
  name: martin-api
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: martin-api
  sessionAffinity: None
  type: LoadBalancer
